Fix compatibility with legacy functions (#708)

diff --git a/bin/run_tests b/bin/run_tests
--- a/bin/run_tests
+++ b/bin/run_tests
@@ -3,6 +3,8 @@
 function usage() {
   >&2 cat << EOF
 
+usage error: $*
+
 $0 [step]
 
 where [step] is one of:
@@ -11,53 +13,83 @@ where [step] is one of:
   schema_tests
   trace_tests
   registrar_tests
-  util_tests
   udmis_tests
-  all_tests
+  util_tests
+  all_tests (except udmis_tests and util_tests)
 EOF
   false
 }
 
+[[ $# == 1 ]] || usage incorrect number of arguments
+
+mkdir -p out
+failures=out/test_failures-$1
+echo -n > $failures
+
+function run_wrap {
+    bin/run_tests $1 || true
+    cat < out/test_failures-$1 >> $failures
+}
+
+function test_wrap {
+    command=$*
+    echo -n "Testing $command: "
+    outfile=out/test_${command//[ \/]/+}
+    result=0
+    if $command > $outfile 2>&1; then
+        echo pass
+    else
+        echo fail, output in $outfile
+        echo $command >> $failures
+    fi
+}
+
 case "$1" in
   install_dependencies)
-    bin/setup_base
-    bin/clone_model
+    test_wrap bin/setup_base
+    test_wrap bin/clone_model
     sudo ln -fs $PWD/bin/udmi /usr/local/bin/
     ;;
   code_tests)
-    bin/gencode check
-    pubber/bin/build check
-    validator/bin/build check
-    bin/test_pylint
+    test_wrap bin/gencode check
+    test_wrap pubber/bin/build check
+    test_wrap validator/bin/build check
+    test_wrap bin/test_pylint
     ;;
   schema_tests)
-    bin/test_schema
-    ;;
-  util_tests)
-    bin/test_locate
+    test_wrap bin/test_schema
     ;;
   trace_tests)
-    bin/test_trace simple
-    bin/test_trace upgrade
-    bin/test_combos
+    test_wrap bin/test_trace simple
+    test_wrap bin/test_trace upgrade
+    test_wrap bin/test_combos
     ;;
   registrar_tests)
-    bin/test_registrar
-    bin/test_sites
+    test_wrap bin/test_registrar
+    test_wrap bin/test_sites
     ;;
   udmis_tests)
-    bin/test_udmis
+    test_wrap bin/test_udmis
+    ;;
+  util_tests)
+    test_wrap bin/test_locate
     ;;
   all_tests)
-    bin/run_tests install_dependencies
-    bin/run_tests code_tests
-    bin/run_tests schema_tests
-    bin/run_tests trace_tests
-    bin/run_tests registrar_tests
-    bin/run_tests util_tests
-    bin/run_tests udmis_tests
+    run_wrap install_dependencies
+    run_wrap code_tests
+    run_wrap schema_tests
+    run_wrap trace_tests
+    run_wrap registrar_tests
+    echo Not including util_tests and udmis_tests
     ;;
   *)
-    usage
+    usage unrecognized step $1
     ;;
 esac
+
+if [[ -s $failures ]]; then
+    echo ====== Test failures: $(tr '\n' ' ' <$failures)
+    false
+else
+    echo ====== All tests passed for $1
+fi
