Don't hardcode local site model

diff --git a/bin/start_local b/bin/start_local
--- a/bin/start_local
+++ b/bin/start_local
@@ -1,6 +1,18 @@
 #!/bin/bash -e
 
 UDMI_ROOT=$(dirname $0)/..
+source $UDMI_ROOT/etc/shell_common.sh
+
+[[ $# == 2 ]] || fail Usage: $0 site_model project_spec
+
+site_model=$(realpath $1)
+project_spec=$2
+shift
+
+echo "export TARGET_PROJECT=${project_spec:-}"
+echo "export UDMI_REGISTRY_SUFFIX=${UDMI_REGISTRY_SUFFIX:-}"
+echo "export UDMI_ALT_REGISTRY=${UDMI_ALT_REGISTRY:-}"
+
 cd $UDMI_ROOT
 
 if [[ ! -d etc/ ]]; then
@@ -9,24 +21,12 @@ if [[ ! -d etc/ ]]; then
     mv var/*.sh etc/
 fi
 
-source $UDMI_ROOT/etc/shell_common.sh
-
-[[ $# == 1 ]] || fail Usage: $0 project_spec
-
-project_spec=$1
-shift
-
-echo "export TARGET_PROJECT=${project_spec:-}"
-echo "export UDMI_REGISTRY_SUFFIX=${UDMI_REGISTRY_SUFFIX:-}"
-echo "export UDMI_ALT_REGISTRY=${UDMI_ALT_REGISTRY:-}"
-
 if [[ ! $project_spec =~ ^//mqtt/ ]]; then
     echo Not a local setup, doing nothing!
     exit 0
 fi
 
-site_model=sites/udmi_site_model
-site_config=sites/udmi_site_model/cloud_iot_config.json
+site_config=$site_model/cloud_iot_config.json
 registry_id=$(jq -r .registry_id $site_config)${UDMI_REGISTRY_SUFFIX:-}
 
 bin/start_etcd
