Test against complete schema directory

diff --git a/bin/test_schema b/bin/test_schema
--- a/bin/test_schema
+++ b/bin/test_schema
@@ -10,7 +10,6 @@ rm -f $errorfile
 
 build=y
 force=n
-parallel=
 
 schemadir=schema
 testdir=tests
@@ -29,11 +28,8 @@ while getopts "d:s:fnp" opt; do
         d)
             testdir=${OPTARG}
             ;;
-        p)
-            parallel=y
-            ;;
         \?)
-            echo "Usage: $0 [-p] [-f] [-n] [-d TEST_DATA_DIR] [-s TEST_SUBSET]"
+            echo "Usage: $0 [-f] [-n] [-d TEST_DATA_DIR] [-s TEST_SUBSET]"
             exit -1
             ;;
     esac
@@ -48,10 +44,6 @@ fi
 
 jarfile=$(realpath validator/build/libs/validator-1.0-SNAPSHOT-all.jar)
 
-if [[ -n $parallel ]]; then
-    echo ========================= Running validation tests in parallel...
-fi
-
 if [[ -z $subsets ]]; then
     subsets=$(cd $testdir; ls -d *.tests)
 fi
@@ -63,6 +55,16 @@ echo Testing against $subsets
 for subset in $subsets; do
     schemaname=${subset%.tests}.json
     testfiles=$(cd $testdir/$subset; ls *.json || true)
+    testbase=$testdir/$subset
+
+    if [[ "$testbase" == "$schemadir" ]]; then
+        reltest=$subset
+    else
+        reldir=$(realpath --relative-to $schemadir $testdir)
+        reltest=$reldir:$subset
+    fi
+    (cd $schemadir; java -jar -Dnashorn.args=--no-deprecation-warning $jarfile -a $schemaname -f $reltest) || true
+
     for testfile in $testfiles; do
         outfile=${testfile%.json}.out
         testbase=$testdir/$subset
@@ -88,26 +90,13 @@ for subset in $subsets; do
           reldir=$(realpath --relative-to $schemadir $testdir)
           reltest=$reldir:$(realpath --relative-to $testdir $testpath)
         fi
-        (
-            (cd $schemadir; java -jar -Dnashorn.args=--no-deprecation-warning $jarfile -a $schemaname -f $reltest) || true
-            if [ $force == y ]; then
-                diff $output $expected || echo Updating $expected && cp $output $expected
-            else
-                diff -b $output $expected || (echo '   ' diff $output $expected | tee -a $errorfile)
-            fi
-        ) &
-
-        if [[ -z $parallel ]]; then
-            wait
+        if [ $force == y ]; then
+            diff $output $expected || echo Updating $expected && cp $output $expected
+        else
+            diff -b $output $expected || (echo '   ' diff $output $expected | tee -a $errorfile)
         fi
     done
 done
-
-if [[ -n $parallel ]]; then
-    sleep 5
-    echo ========================= Waiting for validation results...
-    wait
-fi
 
 echo
 
