initiate mapping process on consuming discovery complete triggger

diff --git a/services/bin/mapping_service b/services/bin/mapping_service
--- a/services/bin/mapping_service
+++ b/services/bin/mapping_service
@@ -1,24 +1,81 @@
-#!/bin/bash -e
+#!/bin/bash
+#
+# Mapping backend service
+#
+set -euo pipefail
 
-UDMI_ROOT=$(dirname $0)/../..
-source $UDMI_ROOT/etc/shell_common.sh
+SCRIPT_ROOT=$(realpath "$(dirname "$0")")
+UDMI_ROOT=$(realpath "$SCRIPT_ROOT/../..")
 
-if [[ $# -ne 6 ]]; then
-    usage registry_id project_id base_cloning_directory project_spec mapping_family discoveryNodeDeviceId
-fi
+source "$UDMI_ROOT/etc/shell_common.sh"
 
-registry_id=$1
-project_id=$2
-base_cloning_directory=$3
-project_spec=$4
-mapping_family=$5
-discoveryNodeDeviceId=$6
+main() {
+    local service_name="Mapping"
+    local message_spec=""
+    local project_spec=""
+    local cloning_dir=""
+    local local_origin_dir=""
+    local is_local=0
+    local should_create=0
 
-shift 6
+    if [[ $# -lt 3 ]]; then
+        # shellcheck disable=SC2102
+        usage message_spec project_spec cloning_dir [--local] [--create] [local_orig_dir]
+    fi
 
-[[ ! -d $UDMI_ROOT/services/src ]] ||
-    up_to_date "$SERVICES_JAR" "$UDMI_ROOT"/services/src ||
-    "$UDMI_ROOT"/services/bin/build
+    message_spec="$1"
+    project_spec="$2"
+    cloning_dir="$3"
+    shift 3
 
+    while [[ $# -gt 0 ]]; do
+        case "$1" in
+            --local)
+                is_local=1
+                shift
+                ;;
+            --create)
+                should_create=1
+                shift
+                ;;
+            *)
+                if [[ -z "$local_origin_dir" ]]; then
+                    local_origin_dir="$1"
+                    shift
+                else
+                    echo "Error: Unknown or duplicate argument '$1'"
+                    usage
+                fi
+                ;;
+        esac
+    done
 
-java -cp "$SERVICES_JAR" com.google.daq.mqtt.mapping.MappingService $registry_id $project_id $base_cloning_directory $project_spec $mapping_family $discoveryNodeDeviceId $@
+    export GCP_PROJECT
+    GCP_PROJECT=$(gcloud config get-value project)
+    echo "Using GCP Project: $GCP_PROJECT"
+
+    export UDMI_PREFIX="${UDMI_NAMESPACE:-}"
+    if [[ -n "$UDMI_PREFIX" ]]; then
+        UDMI_PREFIX="${UDMI_NAMESPACE}~"
+        echo "Using UDMI Namespace Prefix: $UDMI_PREFIX"
+    fi
+
+    if [[ $is_local -eq 1 ]]; then
+        build_services_jar
+    else
+        setup_service_gcp_environment ${service_name}
+    fi
+
+    if [[ $should_create -eq 1 ]]; then
+        local repo_updates_topic="${UDMI_PREFIX}udmi_target"
+        local repo_updates_subscription="${UDMI_PREFIX}udmi_target_mapping_updates"
+        ensure_pubsub_topic_exists "$repo_updates_topic"
+        ensure_pubsub_subscription_exists "$repo_updates_subscription" "$repo_updates_topic" --no-expiration
+    fi
+
+    echo "Starting ${service_name} Service..."
+    java -cp "$SERVICES_JAR" "com.google.daq.mqtt.mapping.MappingService" \
+        "$message_spec" "$project_spec" "$cloning_dir" "$local_origin_dir"
+}
+
+main "$@"
