enable CI tests

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -4,6 +4,8 @@ on:
   push:
     tags:
       - '**'
+    branches:
+      - '**'
   workflow_dispatch:
 
 jobs:
@@ -64,19 +66,91 @@ jobs:
           echo
           docker history $PUSH_TAG
 
-  simple:
-    name: Simple sequence test
+  # simple:
+  #   name: Simple sequence test
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 5
+  #   needs: images
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       device_id: [ "AHU-1", "AHU-22", "GAT-123" ]
+  #   env:
+  #     IMAGE_NAME: ${{ github.repository }}
+  #     REF_NAME: ${{ github.ref_name }}
+  #     DEVICE_ID: ${{ matrix.device_id }}
+  #   steps:
+  #     - name: Setup Environment
+  #       run: |
+  #         sudo apt-get install moreutils
+  #         git clone https://github.com/faucetsdn/udmi_site_model.git
+  #         ln -s udmi_site_model/ site_model
+  #         (cd site_model; git log -n 1)
+  #         jq ".device_id = \"$DEVICE_ID\"" site_model/cloud_iot_config.json | sponge site_model/cloud_iot_config.json
+  #         jq . site_model/cloud_iot_config.json
+  #         docker network create udminet --subnet 192.168.99.0/24
+  #     - name: Start UDMIS container
+  #       run: |
+  #         export IMAGE_TAG=ghcr.io/$IMAGE_NAME:udmis-$REF_NAME
+  #         docker run $IMAGE_TAG cat bin/actualize > /tmp/actualize.sh
+  #         cat /tmp/actualize.sh && bash /tmp/actualize.sh
+  #     - name: Registrar run
+  #       run: |
+  #         docker run --net udminet --name registrar -v $(realpath site_model):/root/site_model \
+  #           ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/registrar site_model/cloud_iot_config.json
+  #     - name: Pubber background run
+  #       run: |
+  #         echo docker run -d --net udminet --name pubber -v $(realpath site_model):/root/site_model \
+  #           ghcr.io/$IMAGE_NAME:pubber-$REF_NAME bin/pubber site_model/cloud_iot_config.json
+  #         docker run -d --net udminet --name pubber -v $(realpath site_model):/root/site_model \
+  #           ghcr.io/$IMAGE_NAME:pubber-$REF_NAME bin/pubber site_model/cloud_iot_config.json
+  #         for count in `seq 0 30`; do
+  #           (docker ps | fgrep -q pubber) || break
+  #           (docker logs pubber 2>&1 | fgrep -q -v "Connection complete") || break
+  #           echo Waiting for pubber startup $((30 - count))...
+  #           sleep 1
+  #         done
+  #         docker logs pubber 2>&1 | fgrep "Connection complete"
+  #     - name: Sequencer run
+  #       run: |
+  #         SEQUENCER_TESTS="broken_config extra_config device_config_acked"
+  #         [[ $REF_NAME =~ test- ]] && SEQUENCER_TESTS=${REF_NAME#test-}
+  #         docker run --net udminet --name sequencer -v $(realpath site_model):/root/site_model \
+  #           ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/sequencer site_model/cloud_iot_config.json \
+  #           $SEQUENCER_TESTS
+  #     - name: Sequencer results
+  #       run: |
+  #         cat site_model/out/devices/$DEVICE_ID/results.md
+  #         if [[ $REF_NAME =~ test- ]]; then
+  #           SPECIFIC_TEST=${REF_NAME#test-}
+  #           more site_model/out/devices/$DEVICE_ID/tests/$SPECIFIC_TEST/*
+  #         else
+  #           [[ $(cat site_model/out/devices/$DEVICE_ID/results.md | egrep 'stable \| [0-9]+ \| (pass|skip)' | wc -l) == 3 ]]
+  #         fi
+  #     - name: UDMIS logs
+  #       if: ${{ !cancelled() }}
+  #       run: |
+  #         docker logs udmis
+  #         more var/tmp/udmis.log
+  #     - name: Registrar logs
+  #       if: ${{ !cancelled() }}
+  #       run: docker logs registrar
+  #     - name: Pubber logs
+  #       if: ${{ !cancelled() }}
+  #       run: docker logs pubber
+  #     - name: Sequencer logs
+  #       if: ${{ !cancelled() }}
+  #       run: docker logs sequencer
+
+  discovery:
+    name: Simple discovery test
     runs-on: ubuntu-latest
     timeout-minutes: 5
     needs: images
-    strategy:
-      fail-fast: false
-      matrix:
-        device_id: [ "AHU-1", "AHU-22", "GAT-123" ]
     env:
       IMAGE_NAME: ${{ github.repository }}
       REF_NAME: ${{ github.ref_name }}
-      DEVICE_ID: ${{ matrix.device_id }}
+      DEVICE_ID: ${{'AHU-1'}}
     steps:
       - name: Setup Environment
         run: |
@@ -92,81 +166,49 @@ jobs:
           export IMAGE_TAG=ghcr.io/$IMAGE_NAME:udmis-$REF_NAME
           docker run $IMAGE_TAG cat bin/actualize > /tmp/actualize.sh
           cat /tmp/actualize.sh && bash /tmp/actualize.sh
+      - name: Generate keys
+        run: |
+          docker run --net udminet --name keygen -v $(realpath site_model):/root/site_model \
+            ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/keygen CERT site_model/devices/$DEVICE_ID
       - name: Registrar run
         run: |
           docker run --net udminet --name registrar -v $(realpath site_model):/root/site_model \
             ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/registrar site_model/cloud_iot_config.json
-      - name: Pubber background run
-        run: |
-          echo docker run -d --net udminet --name pubber -v $(realpath site_model):/root/site_model \
-            ghcr.io/$IMAGE_NAME:pubber-$REF_NAME bin/pubber site_model/cloud_iot_config.json
-          docker run -d --net udminet --name pubber -v $(realpath site_model):/root/site_model \
-            ghcr.io/$IMAGE_NAME:pubber-$REF_NAME bin/pubber site_model/cloud_iot_config.json
-          for count in `seq 0 30`; do
-            (docker ps | fgrep -q pubber) || break
-            (docker logs pubber 2>&1 | fgrep -q -v "Connection complete") || break
-            echo Waiting for pubber startup $((30 - count))...
-            sleep 1
-          done
-          docker logs pubber 2>&1 | fgrep "Connection complete"
-      - name: Sequencer run
-        run: |
-          SEQUENCER_TESTS="broken_config extra_config device_config_acked"
-          [[ $REF_NAME =~ test- ]] && SEQUENCER_TESTS=${REF_NAME#test-}
-          docker run --net udminet --name sequencer -v $(realpath site_model):/root/site_model \
-            ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/sequencer site_model/cloud_iot_config.json \
-            $SEQUENCER_TESTS
-      - name: Sequencer results
-        run: |
-          cat site_model/out/devices/$DEVICE_ID/results.md
-          if [[ $REF_NAME =~ test- ]]; then
-            SPECIFIC_TEST=${REF_NAME#test-}
-            more site_model/out/devices/$DEVICE_ID/tests/$SPECIFIC_TEST/*
-          else
-            [[ $(cat site_model/out/devices/$DEVICE_ID/results.md | egrep 'stable \| [0-9]+ \| (pass|skip)' | wc -l) == 3 ]]
-          fi
-      - name: UDMIS logs
-        if: ${{ !cancelled() }}
-        run: |
-          docker logs udmis
-          more var/tmp/udmis.log
-      - name: Registrar logs
-        if: ${{ !cancelled() }}
-        run: docker logs registrar
-      - name: Pubber logs
-        if: ${{ !cancelled() }}
-        run: docker logs pubber
-      - name: Sequencer logs
-        if: ${{ !cancelled() }}
-        run: docker logs sequencer
-
-  discovery:
-    name: Simple discovery test
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
-    needs: images
-    env:
-      IMAGE_NAME: ${{ github.repository }}
-      REF_NAME: ${{ github.ref_name }}
-    steps:
-      - name: Execute discovery node
+      - name: Start discoverynode
         run: |
           export IMAGE_TAG=ghcr.io/$IMAGE_NAME:misc-$REF_NAME
           # This currently fails (no config), but just check that it actually runs.
-          docker run $IMAGE_TAG discoverynode/bin/run | fgrep "Loading config"
-
-  udmif:
-    name: UDMIF unit tests
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 20.9.0
-      - name: Install Angular CLI
-        run: npm install -g @angular/cli
-      - name: web tests
-        run: echo Disabled udmif/web/runTests due to dependency integration problems
-      - name: api tests
-        run: echo Disabled udmif/api/runTests due to dependency integration problems
+            docker run -d \
+              --net udminet \
+              -v $(realpath site_model):/var/site_model \
+              --name discoverynode \
+              $IMAGE_TAG \
+              bin/run /var/site_model //mqtt/udmis AHU-1 vendor.range=0x65,28179023,20231,,,,,,,,,,,,,,,,
+      - name: Sequencer run
+        run: |
+          docker run --net udminet --name sequencer -v $(realpath site_model):/root/site_model \
+            ghcr.io/$IMAGE_NAME:validator-$REF_NAME bin/sequencer site_model/cloud_iot_config.json \
+            scan_single_future
+      - name: Sequencer results
+        run: |
+          cat site_model/out/devices/$DEVICE_ID/results.md
+          [[ $(cat site_model/out/devices/$DEVICE_ID/results.md | grep -Ec ".*discovery.* pass") == 1 ]]
+      - name: Discoverynode logs
+        if: ${{ !cancelled() }}
+        run: docker logs discoverynode
+  
+  # udmif:
+  #   name: UDMIF unit tests
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 5
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.9.0
+  #     - name: Install Angular CLI
+  #       run: npm install -g @angular/cli
+  #     - name: web tests
+  #       run: echo Disabled udmif/web/runTests due to dependency integration problems
+  #     - name: api tests
+  #       run: echo Disabled udmif/api/runTests due to dependency integration problems
