clean

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -28,11 +28,7 @@ jobs:
           validator/bin/build check
       - name: Schema conformance tests
         if: ${{ always() }}
-        run: |
-          bin/test_schema -p
-      - name: simple trace test
-        run: |
-          bin/test_trace simple
+        run: bin/test_schema -p
       - name: Registrar tests
         if: ${{ always() }}
         run: |
@@ -52,44 +48,32 @@ jobs:
         run: |
           bin/setup_base
           bin/clone_model
-      - name: pubber runs
+      - name: pubber run
         env:
           GCP_TARGET_PROJECT: ${{ secrets.GCP_TARGET_PROJECT }}
         if: "${{ env.GCP_TARGET_PROJECT != '' }}"
         run: |
           bin/test_redirect $GCP_TARGET_PROJECT
-      - name: pubber cmd checks
+      - name: pubber checks
         env:
           GCP_TARGET_PROJECT: ${{ secrets.GCP_TARGET_PROJECT }}
         if: "${{ env.GCP_TARGET_PROJECT != '' }}"
         run: |
-          echo ::::::: pubber.out.1
-          cat pubber.out.1
-          echo :::::::
-          echo Simple checks that a redirect happened and failed
-          fgrep registries/ZZ-TRI-FECTA/devices pubber.out.1
-          fgrep 'system.config.parse success' pubber.out.1
-          fgrep registries/missing/devices pubber.out.1
-          fgrep 'Not authorized to connect' pubber.out.1
-      - name: pubber config checks
-        env:
-          GCP_TARGET_PROJECT: ${{ secrets.GCP_TARGET_PROJECT }}
-        if: "${{ env.GCP_TARGET_PROJECT != '' }}"
+          # Simple checks that a redirect happened and failed
+          set +x
+          fgrep registries/ZZ-TRI-FECTA/devices/GAT-123 pubber.out
+          fgrep 'system.config.parse success' pubber.out
+          fgrep registries/missing/devices/GAT-123 pubber.out
+          fgrep 'Not authorized to connect' pubber.out
+      - name: pubber logs
+        if: ${{ always() }}
         run: |
-          echo ::::::: pubber.out.2
-          cat pubber.out.2
-          echo :::::::
-          echo Check the redirect-by-config setup
-          fgrep registries/ZZ-TRI-FECTA/devices pubber.out.2
-          fgrep 'system.config.parse success' pubber.out.2
-          fgrep registries/reconfigure/devices pubber.out.2
-          fgrep 'Not authorized to connect' pubber.out.2
+          cat pubber.out || true
     
   udmi:
     name: Sequence tests
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    needs: redirect  # Access to UDMI-REFLECTOR is mutually exclusive
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-java@v1
@@ -116,14 +100,9 @@ jobs:
           bin/test_validator $GCP_TARGET_PROJECT
           more /tmp/validator.out
           diff -u /tmp/validator.out etc/validator.out && echo No validator diff detected.
-      - name: output logs
-        env:
-          GCP_TARGET_PROJECT: ${{ secrets.GCP_TARGET_PROJECT }}
-        if: "${{ env.GCP_TARGET_PROJECT != '' }}"
-        run: |
-          cd sites/udmi_site_model/out
-          echo Output from `pwd`
-          more `find out -type f`
+      - name: device output logs
+        if: ${{ always() }}
+        run: more `find udmi_site_model/out/devices/ -type f`
       - name: pubber logs
         if: ${{ always() }}
         run: |
